mongodb/jasper

download.go, download_test.go, jasper_test.go, jrpc/client_test.go, jrpc/internal/service.go, jrpc/util_for_test.go, rest_service.go, rest_test.go
* Also move download-related functions from rest_service.go to download.go
* More tests for download
=> MAKE-387 Clean up download tests and require absolute paths for downloads

harness.go, makefile, manager_basic.go, manager_local.go, manager_self_clearing.go, manager_test.go, process_basic.go, process_test.go, rest_test.go
This `Process` implementation has my ideas for a good `Process` implementation merged into what we had initially on Friday, as well as a bunch of bug fixes.
=> MAKE-523: Re-introduce a better basicProcess

command.go, command_test.go, create.go, create_test.go, harness.go, manager_test.go, output.go, output_test.go, process_basic.go, process_blocking.go, process_test.go, triggers_test.go
Git history is a little wonky because of a self-rebase I did before putting up this PR.
Still need to add doc strings ~and tests for remote command execution~.
=> [WIP] MAKE-624: Add Command to Jasper

command.go
Also remove two redundant convenience Run*() functions.
We forgot this.
=> MAKE-624: Add doc-strings to Command.go

command_test.go
JIRA: https://jira.mongodb.org/browse/MAKE-666
=> MAKE-666: increase TestRunParallelRunsInParallel timeout

evergreen.yaml, harness.go, harness_case.go, makefile
JIRA: https://jira.mongodb.org/browse/MAKE-692
* Fixed benchmarks and added error checks.
* Added benchmarks back to evergreen tasks.
=> MAKE-692: update benchmarks for most recent changes

util.go
JIRA: https://jira.mongodb.org/browse/MAKE-720
=> MAKE-720: close file after write

command.go, command_test.go
JIRA: https://jira.mongodb.org/browse/MAKE-758
=> MAKE-758: correctly set command's output/error and log if unset

cli/service.go, cli/utils.go
JIRA: https://jira.mongodb.org/browse/MAKE-805
I wrote this to make it easier to change the Jasper service configuration and restart it using a single CLI instead of running several commands to achieve it.
=> MAKE-805: add CLI command to force reinstall

command.go, command_test.go
JIRA: https://jira.mongodb.org/browse/MAKE-806
=> MAKE-806: add sudo variants of Add/Append/Extend

rpc/creds.go
JIRA: https://jira.mongodb.org/browse/MAKE-863
=> MAKE-863: omit RPC credentials ServerName

manager_basic.go, process_basic.go, process_blocking.go
JIRA: https://jira.mongodb.org/browse/MAKE-861
=> MAKE-861: do not duplicate options tags on process creation

command.go
JIRA: https://jira.mongodb.org/browse/MAKE-866
=> MAKE-866: return Command from SetInput

rpc/creds.go
JIRA: https://jira.mongodb.org/browse/MAKE-868
=> MAKE-868: add ServerName to JSON-exported RPC credentials

cli/ssh_client.go
JIRA: https://jira.mongodb.org/browse/MAKE-869
=> MAKE-869: suppress logs from SSH

cli/ssh_client.go, cli/ssh_client_test.go
JIRA: https://jira.mongodb.org/browse/MAKE-871
=> MAKE-871: no-op on CloseConnection

cli/client.go, cli/service.go, cli/service_combined.go, cli/service_rest.go, cli/service_rpc.go, cli/service_test.go, cli/ssh_client_test.go, cli/utils.go
JIRA: https://jira.mongodb.org/browse/MAKE-872
=> MAKE-872: allow CLI-started Jasper service to log to splunk

command.go, options/output.go
JIRA: https://jira.mongodb.org/browse/MAKE-951
=> MAKE-951: fix command RedirectErrorToOutput

cli/service.go
JIRA: https://jira.mongodb.org/browse/MAKE-963
=> MAKE-963: splunk token can be read from file

cli/service.go, cli/service_combined.go, cli/service_rest.go, cli/service_rpc.go
JIRA: https://jira.mongodb.org/browse/MAKE-960
=> MAKE-960: add password option for installing service via CLI

download.go, harness.go, interface.go, makefile, manager_basic.go, manager_self_clearing_test.go, manager_test.go, options/file.go, options/log.go, rest/rest_test.go, rest/service.go, rpc/client.go, rpc/client_test.go, rpc/internal/service.go, rpc/service.go, rpc/util_for_test.go, testutil/constants.go, testutil/file.go, testutil/http.go, testutil/options.go, testutil/ports.go, testutil/strings.go, tracker_darwin.go, tracker_freebsd.go, tracker_windows.go
JIRA: https://jira.mongodb.org/browse/MAKE-998
Fix miscellaneous issues.
=> MAKE-998: fix lint, makefile, and service cancellation during process creation

cli/process.go
JIRA: https://jira.mongodb.org/browse/MAKE-1026
=> MAKE-1026: add flags and before funcs for process signal and respawn

LICENSE
JIRA: https://jira.mongodb.org/browse/MAKE-1035
I just copy-pasted this from github.com/evergreen-ci/aviation.
=> MAKE-1035: add LICENSE (Apache 2.0)

makefile, output.go, rpc/client.go, wire/client.go, wire/client_test.go, wire/io.go, wire/process.go, wire/service.go, wire/service_manager.go, wire/service_process.go, wire/util_for_test.go
JIRA: https://jira.mongodb.org/browse/MAKE-1000
* Wire protocol remote client (mostly for testing purposes).
* Copy RPC manager/process tests to wire package.
=> MAKE-1000: implement wire remote client

cli/service.go, cli/service_rest.go, cli/service_rpc.go, cli/service_wire.go
JIRA: https://jira.mongodb.org/browse/MAKE-999
=> MAKE-999: add wire protocol service to CLI

cli/ssh_client.go, makefile, output.go, rpc/client.go, wire/client.go, wire/client_test.go, wire/io.go, wire/process.go, wire/service.go, wire/service_manager.go, wire/service_process.go, wire/util_for_test.go
JIRA: https://jira.mongodb.org/browse/MAKE-898
Was accidentally removed in a previous commit.
=> MAKE-898: re-add ssh log suppression to SSH client

benchmarks/harness.go, manager_synchronized.go, options/create.go, process.go, process_synchronized.go, wire/client_test.go
JIRA: https://jira.mongodb.org/browse/MAKE-1049
=> MAKE-1049: use synchronized instead of unsynchronized

options/remote.go
JIRA: https://jira.mongodb.org/browse/MAKE-1055
Some options are only relevant for using the SSH library.
=> MAKE-1055: validate SSH based on library or client usage

.golangci.yml, cli/command.go, options/log.go
JIRA: https://jira.mongodb.org/browse/MAKE-1056
gocognit complained that `cli.RunCMD` was excessively complex. I basically just turned the log streaming code into its own function.
=> MAKE-1056: refactor CLI run command

subtree_oom.go
In support of https://github.com/evergreen-ci/evergreen/pull/3606
=> EVG-1134 add oomtracker mock

cli/generate.go, cli/util.go, metabuild/generator/golang.go, metabuild/generator/make.go, metabuild/model/common.go, metabuild/model/golang.go, metabuild/model/golang_control.go, metabuild/model/make.go, metabuild/model/output.go
JIRA: https://jira.mongodb.org/browse/EVG-9183
Doc comment improvements. Also, there's [a wiki page](https://github.com/mongodb/jasper/wiki/Evergreen-Metabuild-System) for the metabuild system now.
=> MAKE-9183: improve documentation for metabuild system

evergreen.yaml, makefile
JIRA: https://jira.mongodb.org/browse/EVG-8421
=> EVG-8421: lint benchmarks

oom_tracker_linux.go
We've been missing lines from later on in dmesg.
According to the [docs](https://golang.org/pkg/os/exec/#Cmd.StdoutPipe), `Wait()` will close the pipe when the command exits. If we call Wait in another goroutine before we start reading, whatever's not read at the time the process exits will be lost when the pipe is closed. Calling Wait after we've finished reading (after we've read an EOF) will let us finish reading before the pipe is closed.
These example programs convinced me:
As it is now:
```
package main
import (
"bufio"
"fmt"
"log"
"os/exec"
"time"
)
func main() {
cmd := exec.Command("bash", "-c", "for ((i=1;i<=10;i++)); do echo hi; done")
cmdReader, _ := cmd.StdoutPipe()
if err := cmd.Start(); err != nil {
log.Fatal(err)
}
go func() {
if err := cmd.Wait(); err != nil { …
```
=> EVG-12544 relocate Wait()

process_blocking.go
JIRA: https://jira.mongodb.org/browse/EVG-13211
In the blocking process implementation, it's possible for the process to be signaled, but the process will exit before it checks the result of signaling the process, which will result in it erroneously believing that you're signaling an exited process (one that exited because of the signal it was just sent). In that case, we have to treat it as a special case and check the exit code, which is set to the signal value it received if it is signaled.
=> EVG-13211: do not error if blocking process is signaled and exits because of the signal

remote/internal/service.go
JIRA: https://jira.mongodb.org/browse/EVG-14422
=> EVG-14422: return more context in gRPC errors from SendMessages

internal/executor/executor_test.go, makefile
JIRA: https://jira.mongodb.org/browse/EVG-14468
* Fix two flaky tests due to processes exiting too soon.
* Fix small makefile bug.
=> EVG-14468 fix flaky tests

options/create.go
add nil check for nil stat and check errors
I feel like it looks a bit ugly but wasn't sure if there was a better way
=> DEVPROD-14445 Add nil check to create validate
