jrpc/client.go, makefile
Pretty simple change should let us ensure we guarantee that _all_ our entries in `_testPackages` have passed.
=> MAKE-587: Failure to compile JRPC code does not lead to Evergreen task failure

harness.go, integration_test.go, interface.go, jasper_test.go, jrpc/client.go, jrpc/client_test.go, jrpc/internal/service.go, manager_self_clearing_test.go, manager_test.go, process_blocking.go, process_blocking_test.go, process_local.go, process_test.go, rest_client.go, rest_service.go, rest_test.go, signal.go, triggers_test.go
Added a self-review comment to this patch because there is something in particular that bothers me about what we are doing here.
=> MAKE-520: Retrieve the exit code from calling Wait() in jasper

makefile
This also adds some logic that ensures that the benchmark actually passes.
We may want to prefer using "^FAIL" instead here, just to be consistent with MAKE-587.
=> MAKE-571: Increase timeout for Jasper benchmarks (also check that they pass)

jrpc/client_test.go, jrpc/internal/service.go
I've decided to just change the error returns for `Wait()` and `Signal()` to `nil` so that their `OperationOutcome` returns actually make it through gRPC.
It may be worth it to do something similar to other times where we return `(*OperationOutcome, error)` and its better to send over the `*OperationOutcome` instead.
=> MAKE-525: Errors with sending signal to terminated processes, some other clean up

jrpc/client_test.go, process_test.go, rest_client.go
We were calling `proc.Info()` without calling `proc.Wait()` and expecting consistent results. This is an incorrect use of Jasper. Took some time to realize that the bug was not in Jasper logic, but in the test logic. Oh well.
Also a slight fix to a debug statement that was calling `wrapError()` around potentially `nil` errors, which causes some ugly and misleading log output.
=> MAKE-581: InfoHasMatchingID occasionally fails for Jasper process tests

jrpc/client_test.go, jrpc/internal/service.go, manager_basic.go, manager_test.go, process_blocking.go, rest_service.go
Fundamentally, the problem here is twofold:
1. We were polluting context use by mixing up the request context with the context used by the process, which isn't a good thing especially when the process methods can hang.
2. We were calling `proc.Info()` in multiple parts of the codebase without calling `proc.Wait()`, which can lead to hangs, especially if the context used has no deadline.
It is possible that this may resolve [MAKE-523](https://jira.mongodb.org/browse/MAKE-523).
=> MAKE-569, MAKE-601: Fix TestManagerInterface/REST failures on RACE, Fix context deadline exceeded errors for JRPC process creation

create.go, download.go, filter.go, jrpc/client.go, jrpc/internal/jasper.ext.go, jrpc/internal/service.go, jrpc/service.go, manager_local.go, output.go
Also some re-ordering of things in `jasper.ext.go` to be consistent.
=> MAKE-584: Add missing documentation comments to Jasper

integration_test.go, interface.go, jrpc/client_test.go, jrpc/service_test.go, process_basic.go, process_blocking.go, process_blocking_test.go
These are some tests elsewhere in the codebase where I forgot to add `basicProcess`.
=> MAKE-537: Add some missing tests for basicProcess in JRPC & integration_test.go

process_basic.go, process_blocking.go, process_test.go, rpc/client_test.go, rpc/internal/service.go
Had to do some Windows-specific rigging of the tests, since signal numbers like 9 and 15 for `SIGKILL` and `SIGTERM` don't exist on Windows.
=> MAKE-630: Improve exit code return from Jasper RPC Wait() calls

interface.go, jasper_test.go, manager_test.go, process_basic.go, process_blocking.go, process_blocking_test.go, process_local.go, process_test.go, rest_client.go, rest_test.go, rpc/client.go, rpc/client_test.go, triggers.go
* Added function to register triggers before signals
* Changed blocking process so that it doesn't wait until the process finishes to populate ProcessInfo. Instead of checking if `*ProcessInfo` exists (which only occurs when `Wait()` returns), blocking process now checks if `ProcessInfo.Complete` is set (this is also more consistent with basic process).
* Trivial spellcheck stuff
=> MAKE-639: add pre-signal trigger for basic and blocking processes

command.go, create.go, create_test.go, manager_local.go, triggers.go
JIRA: https://jira.mongodb.org/browse/MAKE-670
CreateOptions closers was changed in MAKE-624 so the functions now return errors. This just updates `(*CreateOptions) Close()` to propagate the errors. It also makes it more consistent with the other `Close()` functions.
=> MAKE-670: make (*CreateOptions) Close() consistent with other close functions

create.go, manager_test.go, output.go, process_basic.go, process_blocking.go, process_test.go, rpc/internal/jasper.ext.go, triggers.go, triggers_test.go
JIRA: https://jira.mongodb.org/browse/MAKE-680
* Added copy function.
* Copied all CreateOptions in any place that spawns new processes.
* Added more documentation for CreateOptions.
=> MAKE-680: clone CreateOptions before spawning new processes with them

command_test.go, process_blocking.go, process_blocking_test.go
JIRA: https://jira.mongodb.org/browse/MAKE-681
* Blocking process operations (e.g. `Info()`) won't wait until context is done if the `ops` channel stops processing operations (when `reactor` returns).
=> MAKE-681: fix potential hang until context is done in blocking process if the process finishes while an operation is waiting to be processed.

process_blocking.go
JIRA: https://jira.mongodb.org/browse/MAKE-673
This test was failing because triggers run after the process state is considered complete (so the loggers are not flushed until after the process is complete).
=> MAKE-673: ensure triggers run before the process is marked as complete

process_blocking.go
Otherwise there's a data race.
=> MAKE-709: lock triggers before running when process completes

rpc/client.go, rpc/client_test.go, rpc/service.go, rpc/service_test.go, rpc/service_windows_test.go, rpc/util_for_test.go
JIRA: https://jira.mongodb.org/browse/MAKE-707
* Add option to specify TLS credentials.
=> MAKE-707: add more usable constructor for RPC server/client

command.go, command_test.go
JIRA: https://jira.mongodb.org/browse/MAKE-756
* Local/remote commands use all options set by user in `CreateOptions` (they were ignoring all options set except working directory).
* Made a ticket for a logic bug in how output/error is handled by `Command` if redirection/suppression is used.
* Minor doc comment fixes.
=> MAKE-756: Command should respect its CreateOptions settings 

command.go
JIRA: https://jira.mongodb.org/browse/MAKE-756
Okay, this one should actually allow a command to run over SSH with the environment. The previous commit didn't work due to how the command after the ssh args are interpreted.
=> MAKE-756: fix env due to shell interpretation

create.go, create_test.go
JIRA: https://jira.mongodb.org/browse/MAKE-770
* Fixes shell quoting in Evergreen expansions.
=> MAKE-756: fix issue with nested shell quotes

download.go, download_test.go
JIRA: https://jira.mongodb.org/browse/MAKE-728
* Timeout was because it had to download the entire mongo .tar.gz, which was taking a long time on Windows.
=> MAKE-728: fix TestProcessDownloadJob timeout

command.go
JIRA: https://jira.mongodb.org/browse/MAKE-790
* Only valid for commands run with `Command.Run()`, not `Command.RunParallel()`.
=> MAKE-790: add Wait to Command to check exit code

create.go, create_test.go, harness.go, process_basic.go, process_blocking.go, process_blocking_test.go, process_test.go, rest_service.go
JIRA: https://jira.mongodb.org/browse/MAKE-736
* `ProcessInfo.Timeout` is set by processes when `exec.Command` is killed by timeout.
* Fixed minor bug in handling timeout on REST `CreateProcess()`.
=> MAKE-736: detect when process has timed out

command.go
JIRA: https://jira.mongodb.org/browse/MAKE-790
* Fixes a race in `RunParallel` due to `Command.procs` being copied between Commands.
=> MAKE-790: fix RunParallel race to append to procs

cli/utils.go
JIRA: https://jira.mongodb.org/browse/MAKE-764
* Set default port for `jasper client` ops depending on whether it's a REST/RPC service.
=> MAKE-764: set CLI default port values for client operations

cli/service_rest.go, cli/service_rpc.go
JIRA: https://jira.mongodb.org/browse/MAKE-804
The numbers don't mean anything, but it avoids conflicting with Evergreen, which uses ports around 2285.
=> MAKE-804: change default Jasper ports

manager_self_clearing.go, process_basic.go
JIRA: https://jira.mongodb.org/browse/MAKE-767
* Deadlock was because a test attempted to send `SIGTERM` via `Process.Signal()` and recursively read lock the `RWMutex` in `basicProcess`.
=> MAKE-767: remove recursive read lock in Signal

process_basic.go
JIRA: https://jira.mongodb.org/browse/MAKE-801
* Since a process's ID never changes after first initialization, it doesn't need a lock.
* Removed the initialize step from `(*basicProcess).transition()` because the values can be set before the goroutine starts in `newBasicProcess`.
=> MAKE-801: remove unnecessary locks from basic process

cli/cli.go, cli/client.go, cli/io.go, cli/io_test.go, cli/manager.go, cli/process.go, cli/service.go
JIRA: https://jira.mongodb.org/browse/MAKE-807
* Convenience functions to convert JSON output from CLI commands to structs.
* Added consts for CLI subcommand names.
=> MAKE-807: make it easier to parse JSON CLI output into response structs

cli/command.go, cli/io.go, cli/service.go, process_test.go, rpc/client.go, rpc/client_test.go, rpc/internal/service.go
JIRA: https://jira.mongodb.org/browse/MAKE-830
Miscellaneous fixes and improvements.
* Fix some usage strings.
* Fix logging issue where process ID wasn't used.
* Ensure processes with in-memory logger get to write output/error even if a subcommand fails.
* Fix issue where non-waited commands weren't backgrounded properly.
* Make some RPC errors more descriptive.
* `service status` command writes readable JSON string output for status.
=> MAKE-830: various fixes to user CLI; improve service status command readability

command.go, command_test.go, manager_basic.go
JIRA: https://jira.mongodb.org/browse/MAKE-832
Apply tags to all underlying processes of command.
=> MAKE-832: fix tag handling for processes spawned by Command

cli/command.go, cli/utils.go, rpc/client.go, rpc/internal/service.go, signal.go
JIRA: https://jira.mongodb.org/browse/MAKE-832
* Fix minor issues in Jasper user CLI when waiting.
* Fix an RPC issue where wait returns an oblique error if the exit code is nonzero (this should be handled by the caller anyways, who should handle the exit code themselves).
=> MAKE-832: fix wait on Jasper user CLI; fix RPC success checking on Wait

rpc/client_test.go, rpc/creds.go
JIRA: https://jira.mongodb.org/browse/MAKE-839
Allows server to present the correct credentials to the client if the client connects to a server on an IP that doesn't match the server's certificate.
=> MAKE-839: add optional ServerName for Credentials

cli/service.go, cli/service_combined.go, cli/service_rest.go, cli/service_rpc.go
JIRA: https://jira.mongodb.org/browse/MAKE-849
Add option to set the user running the service.
=> MAKE-849: add user option for CLI-started service

command.go, command_test.go
JIRA: https://jira.mongodb.org/browse/MAKE-808
When given a command with only one arg, there is a check to ensure that we are not accidentally passing a shell command, but currently, this `strings.Contains` is never true because it looks for a substring instead of looking for each individual character. `Command` will now check if it is actually a shell command by checking for any shell-syntax characters (space, double quote, single quote) inside the first arg (i.e. the program name).
=> MAKE-808: correctly check for shell command

cli/ssh_process.go
JIRA: https://jira.mongodb.org/browse/MAKE-870
=> MAKE-870: only return error from CLI over SSH Wait() if error text is non-empty

cli/utils_for_test.go, download_test.go, jasper_test.go, manager_test.go, process_blocking_test.go, process_test.go, rest_client.go, rest_test.go, rest_windows_test.go, rpc/internal/service.go, utils.go, vendor/github.com/tychoish/bond/util.go
JIRA: https://jira.mongodb.org/browse/MAKE-817
Instead of downloading the mongo tarball and extracting it, the REST service download test just downloads a tiny test file. Hopefully this will make this test less flaky.
=> MAKE-817, MAKE-840: fix various download test issues

cli/manager_test.go, cli/process_test.go, cli/remote_test.go, cli/remote_unix_test.go, cli/remote_windows_test.go, cli/service.go, cli/service_combined.go, cli/service_rest.go, cli/service_rpc.go, cli/service_test.go, cli/ssh_client_test.go, cli/ssh_process_test.go, cli/util_for_test.go, cli/util_test.go
JIRA: https://jira.mongodb.org/browse/MAKE-938
* Suppresses errors from running an operation, mostly to suppress errors from calling commands multiple times.
* Use testutil constants
=> MAKE-938: allow service operations to run in quiet mode

cli/service.go, cli/service_combined.go, cli/service_rest.go, cli/service_rpc.go
MAKE-939: https://jira.mongodb.org/browse/MAKE-939
The Jasper service can run as a user agent if not running with root.
=> MAKE-939: allow launchd daemons to run as a user agent

command.go, command_test.go
JIRA: https://jira.mongodb.org/browse/MAKE-809
* Add tests for wait.
* Remove unused duplicate functions from old code.
=> MAKE-809: improve Command test coverage

command.go
JIRA: https://jira.mongodb.org/browse/MAKE-969
The remote host already parses the command string through bash when running over SSH.
=> MAKE-969: avoid prematurely parsing the SSH command string

glide.lock
JIRA: https://jira.mongodb.org/browse/MAKE-976
Removed github.com/surullabs/lint since it's not in the vendor directory nor does anything seem to be using it.
=> MAKE-976: remove unused lint package

process_basic.go, process_blocking.go, process_blocking_test.go, process_test.go
JIRA: https://jira.mongodb.org/browse/MAKE-988
This is primarily to avoid confusion about `Info()` returning different tags from `GetTags()`.
=> MAKE-988: synchronize process info tags and process tags field

rest/service.go, rpc/internal/service.go, rpc/service.go
JIRA: https://jira.mongodb.org/browse/MAKE-1002
* Handle cache pruning panics in the RPC service.
* Stop the cache pruning for the RPC service when the service is closed.
=> MAKE-1002: standardize cache pruning behavior

command.go, options/remote.go
JIRA: https://jira.mongodb.org/browse/MAKE-1027
I accidentally removed `ExtendRemoteArgs()`.
=> MAKE-1027: re-add ExtendRemoteArgs and export RemoteConfig

glide.lock, options/log.go, options/output.go, process_test.go, vendor/github.com/mongodb/grip/send/base.go, vendor/github.com/mongodb/grip/send/buffered.go, vendor/github.com/mongodb/grip/send/buffered_test.go, vendor/github.com/mongodb/grip/send/internal.go, vendor/github.com/mongodb/grip/send/send_test.go
JIRA: https://jira.mongodb.org/browse/MAKE-1150
Files were not being closed because the underlying file send.Senders were not being closed due to WriterSender not closing its underlying sender. This closes the output's `Loggers` but not the `Output` field. It also revendors grip to ensure the buffered sender closes the underlying sender on `Close()`
=> MAKE-1150: fix file handles in Windows tests

glide.lock, manager_windows_test.go, options/log.go, options/output.go, vendor/github.com/mongodb/grip/send/annotating.go, vendor/github.com/mongodb/grip/send/async_group.go, vendor/github.com/mongodb/grip/send/buffered.go, vendor/github.com/mongodb/grip/send/buffered_test.go, vendor/github.com/mongodb/grip/send/error_handler.go, vendor/github.com/mongodb/grip/send/interface.go, vendor/github.com/mongodb/grip/send/multi.go, vendor/github.com/mongodb/grip/send/writer.go
JIRA: https://jira.mongodb.org/browse/MAKE-1150
Since we have no guarantees on who owns the sender after you wrap it, this both closes the wrapper sender and the base sender. This assumes that potentially closing senders multiple times is acceptable.
=> MAKE-1150: close logger's underlying senders

cli/ssh_client.go, glide.yaml
JIRA: https://jira.mongodb.org/browse/MAKE-1159
This disables pty allocation since we're running in non-interactive mode anyways and prevent user from running in verbose mode.
Unrelated, but also cleans up some of the glide yaml packages.
=> MAKE-1159: enforce non-interactive options in SSH client

cli/service.go
JIRA: https://jira.mongodb.org/browse/MAKE-1165
This is undocumented, but passing `SessionCreate` to launchd creates a user security session to give access to the user keychain.
=> MAKE-1165: create security session for macos

cli/service.go, glide.lock, vendor/github.com/evergreen-ci/service/service.go, vendor/github.com/evergreen-ci/service/service_darwin.go
JIRA: https://jira.mongodb.org/browse/MAKE-1174
I'm going to try more things to diagnose the problems on the mac hosts and test the hypothesis that maybe the launchctl daemon is excessively limiting the agent's resources. This option tells launchd to not apply resource limits to Jasper (and by extension, the agent). See [the relevant StackExchange post](https://apple.stackexchange.com/questions/322557/why-is-an-application-running-so-slowly-when-started-with-launchctl).
=> MAKE-1174: specify process type for launchd

cli/command.go, cli/service.go, cmd/run-linter/run-linter.go, makefile
JIRA: https://jira.mongodb.org/browse/MAKE-1149
I'm moving all MAKE repos to use golangci-lint. This just updates the version since Jasper already uses golangci-lint.
=> MAKE-1149: update golangci-lint

job_test.go, output_test.go
JIRA: https://jira.mongodb.org/browse/MAKE-1179
I ran the logging test on a Windows spawn host many times, but I can't reproduce the hang. I'm going to say it works (or at the very least, the problem is probably something in the agent environment and not due to the test itself) unless the problem appears again.
=> MAKE-1179: fix test name

buildsystem/model/build.go, evergreen.yaml, makefile, output_test.go
JIRA: https://jira.mongodb.org/browse/MAKE-1311
* Define jasper build target structure.
* I left some open questions since some parts of the jasper build example syntax weren't clear on their purpose.
* Add lint-jasper to evergreen tasks.
=> MAKE-1311: define basic jasper build syntax structure

metabuild/generator/golang.go, metabuild/generator/golang_test.go, metabuild/model/common.go, metabuild/model/golang.go, metabuild/model/golang_control.go, metabuild/model/golang_test.go, metabuild/model/make.go, metabuild/model/make_control.go, metabuild/model/util.go
JIRA: https://jira.mongodb.org/browse/MAKE-1369
* Users can specify package-specific and variant-specific environment variables.
* Environment precedence: global env < package env < variant env
* We don't let users specify their `GOPATH` on a package level because this would cause various problems with the fact that the `GOPATH` is used to determine the project clone directory and task group behavior would be undesirable if the `GOPATH` could change for each package.
=> MAKE-1369: allow package and variant level environment variables

metabuild/generator/golang.go, metabuild/generator/golang_test.go, metabuild/model/golang.go, metabuild/model/golang_test.go
JIRA: https://jira.mongodb.org/browse/MAKE-1371
The metabuild has a feature for go projects to automatically create task definitions on a per-package basis without you having to explicitly list all the packages (it does this by walking the project directory tree). Right now, the generator will only auto-discover go packages if they have `*_test.go` files in them. This adds an option to auto-discover any package that contains a go file in it (`*.go`).
=> MAKE-1371: allow package discovery to include source-only directories

subtree_oom.go, subtree_oom_test.go
The parsing was relying on a space after the pid, which wasn't true on rhel
```
Killed process 9823, UID 0, (FlowCon.fresher) total-vm:3098244kB, anon-rss:1157280kB, file-rss:36kB
```
=> EVG-9706 use regexp

metabuild/generator/golang.go, metabuild/generator/golang_test.go
JIRA: https://jira.mongodb.org/browse/EVG-12388
We have to do this for Golang, because if you generate the config on your local machine, the working directory won't exist on the host. The working directory will be automatically set to be the agent's default working directory for the task.
=> EVG-12388: do not set subprocess.scripting working directory in generator

process_test.go, remote/process_test.go
JIRA: https://jira.mongodb.org/browse/EVG-8507
I'm not actually certain that this is the problem, but cancel the context before sending the request for `Wait()` (which should cause the process to start and then should be terminated). It should not be necessary to terminate the process after the process has already returned from `Wait()`.
=> EVG-8507: fix test that depends on timing of context cancellation

makefile, metabuild/generator/make.go, metabuild/generator/util.go, metabuild/generator/util_test.go
JIRA: https://jira.mongodb.org/browse/EVG-8852
I tested generating `evergreen.yaml` for Jasper with the Make generator.
* Make file reports run as "setup" commands so that they do not fail a task (e.g. if no files are found).
* Continue on error for make targets (this may or may not be the most sane setting).
=> EVG-8852: fixup small inconveniences in Make generator

cli/util.go, manager_basic.go, manager_test.go, options/create.go, remote/client_test.go, remote/process_test.go, remote/rest_client.go, remote/rest_service.go, remote/rpc_util_test.go
JIRA: https://jira.mongodb.org/browse/EVG-9110
* Add tests that were missing from the remote tests but were present in the root package tests.
* Fix REST manager logging and scripting cache to pass tests.
* Add REST manager to remote manager tests.
=> EVG-9110: add REST client to remote tests

cli/generate.go, metabuild/generator/golang.go, metabuild/generator/golang_test.go, metabuild/model/common.go, metabuild/model/golang.go, metabuild/model/golang_control.go, metabuild/model/golang_test.go, metabuild/model/make.go, metabuild/model/make_control.go, metabuild/model/util.go
JIRA: https://jira.mongodb.org/browse/EVG-12493
The working directory you pass to the CLI used to have inconsistent meaning - for Golang, it was the directory containing the GOPATH while for Make, it was the directory where the task git clones the project. This was done for a slightly silly reason related to the Golang generator's automatic package discovery. Now, it's consistent and it means the directory where git clone occurs (which is configurable by the user). I'll update the docs once this is merged.
* Allow working directory (i.e. git clone directory for task) to be set within YAML config file for Golang and Make.
* Use new CLI flag to determine directory where Golang package discovery occurs.
* Automatic package discovery does not depend on working directory anymore.
=> EVG-12493: change working directory semantics

cli/remote.go, cli/ssh_client.go, options/logging.go, options/logging_test.go, remote/internal/service.go, remote/mdb_client.go, remote/mdb_io.go, remote/mdb_service.go, remote/mdb_service_logging.go, remote/rest_service.go
JIRA: https://jira.mongodb.org/browse/EVG-12467
* Implement SendMessages for the CLI and CLI over SSH.
* Add validation for correct logging payloads.
* Fix some misnaming in mongo wire protocol logging.
* We can't test this until [this ticket](https://jira.mongodb.org/browse/EVG-12626) is completed since `SendMessages()` relies on the logging cache.
=> EVG-12467: implement SendMessages for CLI

cli/command.go, remote/internal/jasper.ext.go, remote/rpc_client.go, remote/rpc_service.go
JIRA: https://jira.mongodb.org/browse/EVG-12738
If the gRPC timestamp type or gRPC duration type is unset (e.g. the process hasn't ended yet so it hasn't set an end timestamp for the process), it'll fail to convert the protobuf time/duration type into the equivalent standard library time type.
* Handle nil timestamps/durations from gRPC.
* Minor fix to handle contexts better in CLI code.
* Minor updates to documentation.
=> EVG-12738: handle nil times and durations from gRPC

logging_cache.go, remote/client_test.go, remote/logging_cache_test.go, remote/mdb_client_logging_cache.go, remote/mdb_io.go, remote/mdb_service_logging.go, remote/rest_service.go, remote/scripting_test.go
JIRA: https://jira.mongodb.org/browse/EVG-12920
* Add more tests for remote LoggingCache. Some of them can't be written until [EVG-13100](https://jira.mongodb.org/browse/EVG-13100) and [EVG-13101](https://jira.mongodb.org/browse/EVG-13101) are done.
* Split up the test cases for tidiness.
=> EVG-12920: add remote LoggingCache tests and split up remote tests by interface

cli/service.go, glide.lock, vendor/github.com/evergreen-ci/service/service.go, vendor/github.com/evergreen-ci/service/service_darwin.go, vendor/github.com/evergreen-ci/service/service_systemd_linux.go, vendor/github.com/evergreen-ci/service/service_sysv_linux.go, vendor/github.com/evergreen-ci/service/service_upstart_linux.go, vendor/github.com/evergreen-ci/service/service_windows.go
JIRA: https://jira.mongodb.org/browse/EVG-13121
Even if the Jasper CLI is running in a non-interactive session, specifying `--interactive` will force it to run as if in an interactive session.
=> EVG-13121: add CLI flag to force run a service in an interactive session

cli/scripting.go, mock/manager.go, mock/remote.go, options/scripting.go, options/scripting_golang.go, options/scripting_python.go, options/scripting_roswell.go, remote/internal/service.go, remote/mdb_service_scripting.go, remote/rest_service.go, remote/scripting_test.go, scripting/scripting.go, scripting/scripting_golang.go, scripting/scripting_python.go, scripting/scripting_test.go, testutil/options.go
JIRA: https://jira.mongodb.org/browse/EVG-12926
* Add more test coverage for remote scripting harness interface.
* Fix bug where `Setup()` suppresses errors for Golang and Python scripting environments.
* Clean up dead code in RPC scripting service.
* Minor renaming across tests to use "sh" variable name instead of "se".
=> EVG-12926: add remote scripting tests

integration_test.go, options/create_test.go, process_blocking.go, tracker_linux.go
JIRA: https://jira.mongodb.org/browse/EVG-13211
* Some of the MacOS hosts don't have `go` in their `PATH`, so I changed the test so it does not rely on its existence.
* **Make the functions in the operations-processing channel in blocking process implementation non-blocking.** When we call process method (e.g. `Info()`), the blocking process implementation enqueues an operation in the process's operations channel, which is responsible for running the operation. However, if the process method does not receive the result from the operation (e.g. the context cancels so the process method returns early), it can cause the goroutine to hang, which causes a slow resource leak due to process methods returning without receiving from the operation they created up.
* **Fix an issue where the …
=> EVG-13211: fix MacOS flaky tests

cli/service.go, cli/service_base.go, cli/service_combined.go, cli/service_rest.go, cli/service_rpc.go, cli/service_test.go, cli/service_wire.go, options/logger.go
JIRA: https://jira.mongodb.org/browse/EVG-13294
* Add CLI flag to check commands as preconditions for starting the Jasper server. If it's not met, the daemon exits without starting the Jasper server. For example, if you pass it a shell script and the script returns an error, Jasper will not start. Because Jasper service files are written to restart whenever the daemon exits, the daemon will poll the precondition until it succeeds, at which point the Jasper service will begin running.
* Refactor service daemons slightly for code tidiness.
=> EVG-13309: add support for precondition checks before starting service

remote/mdb_service.go, remote/process_test.go, testutil/http.go, tracker_linux.go
JIRA: https://jira.mongodb.org/browse/EVG-13532
* Only send SIGKILL if SIGTERM fails when cleaning up tracked Linux processes.
* Minor fix for converting int (i.e. char) to string since go1.15 will complain.
* Minor doc comment fixes.
=> EVG-13532: send SIGKILL in Linux process tracker cleanup

integration_test.go, interface.go, process_blocking.go
JIRA: https://jira.mongodb.org/browse/EVG-13592
The integration test has an occasional flaky run on Windows only when run in CI for unknown reasons (on a spawn host, i can't reproduce it). While I don't know if this will fix it completely, this should make it slightly less likely to flake by reducing the chance of resource leaks. I ran it ~20 times in CI and it didn't fail.
* Ensure goroutines exit when context cancels to avoid leaking goroutines in tests.
* Use omitempty for process info since it shouldn't show the process start/end time when it's unset.
=> EVG-13592: exit goroutines when context cancels in integration test

cli/service_test.go, cli/util_for_test.go, download_test.go, remote/client_test.go, remote/mdb_util_test.go, remote/rest_util_test.go, testutil/http.go
JIRA: https://jira.mongodb.org/browse/EVG-13187
This fixes an issue where wire protocol tests occasionally fail because the service can't listen on the port we choose on Windows. I ran it a bunch of times and it seems to succeed consistently now.
=> EVG-13187: try different ports to start the MDB service

cli/service_test.go, cli/util_for_test.go, download_test.go, options/download.go, remote/client_test.go, remote/client_windows_test.go, remote/logging_cache_test.go, remote/process_test.go, remote/rest_client.go, remote/rest_service_test.go, remote/rest_util_test.go, remote/rpc_util_test.go, remote/scripting_test.go, testutil/http.go
JIRA: https://jira.mongodb.org/browse/EVG-9288
* Use utility package instead of testutil/bond.
* Make a new HTTP client constructor to create REST clients that don't own the HTTP clients given to them.
* Fix an issue where an HTTP client would be freed back into the pool more than once, which caused REST tests to hang.
=> EVG-9288: use utility HTTP clients

remote/rest_client_process.go, remote/rest_service.go, remote/rest_service_test.go
JIRA: https://jira.mongodb.org/browse/EVG-13672
The REST service used to just return the exit code, which is not as useful as getting the original error text as well from `Wait`. This makes the REST interface behave the same as the other interfaces.
=> EVG-13672: return error message from Wait() in REST service

mock/oom_tracker.go, oom_tracker.go, oom_tracker_darwin.go, oom_tracker_linux.go
Include the actual lines from dmesg so the agent can print them in the logs.
Continue to parse out the PIDs though, since they're sent back to the app server and displayed on the task page.
=> EVG-13734 report OOM lines

go.mod, go.sum
Jira: https://jira.mongodb.org/browse/EVG-15628
Bump Bond version to depend on archiver/v3.
=> EVG-15628: bump Bond version

go.mod, go.sum, internal/executor/docker.go, internal/executor/docker_signals.go, internal/executor/docker_test.go, internal/executor/executor_test.go, options/create.go, options/docker.go
Jira: https://jira.mongodb.org/browse/EVG-15734
* Bump Docker to the latest stable version. Since Docker isn't using Go modules, it's always risky to upgrade the Docker library without some caution because we can only have one version of Docker across all our repos.
* Add a field for CPU architecture. We already populate the OS, but Docker's `ContainerCreate` API call now requires you to specify the OS/arch, so we have to pass both of them as part of the options.
* Improve the way options are passed to the Docker executor a bit.
=> EVG-15734: upgrade Docker to v20.10.11

makefile, remote/internal/jasper.pb.go
JIRA: https://jira.mongodb.org/browse/EVG-15699
Note: I think we originally compiled the pb files with a different version of `protoc` so it changed slightly.
=> EVG-15699: Pin protobuf version

options/create.go
If `OverrideEnviron` is set, [the child process will _not_ inherit the current process's environment](https://github.com/mongodb/jasper/blob/6d9ec4246500a4c9c7d4006d29f053c920e9dc18/options/create.go#L232) (this is what Go exec does by default), so the original doc was the opposite of the actual behavior. I updated the wording.
=> docs: fix explanation of OverrideEnviron

command.go, internal/executor/executor.go, internal/executor/local_default.go, internal/executor/local_unix.go, internal/executor/ssh_binary.go, options/create.go
[DEVPROD-10457](https://jira.mongodb.org/browse/DEVPROD-10457)
I will open an Evergreen PR shortly that will use this to make each process started by shell.exec and subprocess.exex a group leader.
=> DEVPROD-10457 set group leader
